version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: php:5.6-cli
    steps:
      - checkout
      - run:
          command: |
            composer install
            ./phpunit.sh
